import type { Vector3Tuple } from 'three';

/** Shared dimensions and asset layout for the architectural house feature. */
export const HOUSE_CONFIG = {
  ROOT_POSITION: [0, 0, -18] as Vector3Tuple,
  FLOOR_HEIGHT: 3.2,
  WALL_HEIGHT: 2.82,
  WALL_THICKNESS: 0.18,
  SLAB_THICKNESS: 0.18,
  BASEBOARD_HEIGHT: 0.09,
  BASEBOARD_DEPTH: 0.045,
  HOUSE_BOUNDS: {
    MIN_X: -12,
    MAX_X: 12,
    MIN_Z: -11,
    MAX_Z: 11,
  },
  BALCONY: {
    MIN_X: -5,
    MAX_X: 5,
    MIN_Z: 11,
    MAX_Z: 15,
  },
  INTRO_TOUR: {
    ENABLED: true,
    PLAYER_END_POSITION: [0, 0, -30.5] as Vector3Tuple,
    WAYPOINTS: [
      {
        position: [0, 4.8, -56] as Vector3Tuple,
        target: [0, 1.7, -28] as Vector3Tuple,
        duration: 1.7,
      },
      {
        position: [-6.8, 3.2, -35] as Vector3Tuple,
        target: [0, 1.8, -28.8] as Vector3Tuple,
        duration: 1.8,
      },
      {
        position: [0, 2.0, -30.6] as Vector3Tuple,
        target: [0, 1.35, -24.8] as Vector3Tuple,
        duration: 1.9,
      },
    ],
  },
} as const;

/** Interactive rooms/zones represented by selectable wall materials. */
export const HOUSE_ROOMS = [
  {
    id: 'foyer',
    label: 'Foyer',
    floor: 0,
    bounds: { minX: -3, maxX: 3, minZ: -11, maxZ: -6 },
    defaultWallpaper: 'linenWarm',
    wallpaperIds: ['linenWarm', 'paintedPlaster', 'jacquardSoft'],
  },
  {
    id: 'hall',
    label: 'Stair Hall',
    floor: 0,
    bounds: { minX: -3, maxX: 3, minZ: -6, maxZ: 11 },
    defaultWallpaper: 'paintedPlaster',
    wallpaperIds: ['paintedPlaster', 'linenWarm', 'fabricNeutral'],
  },
  {
    id: 'living',
    label: 'Living Room',
    floor: 0,
    bounds: { minX: -12, maxX: -3, minZ: -11, maxZ: 11 },
    defaultWallpaper: 'fabricNeutral',
    wallpaperIds: ['fabricNeutral', 'linenWarm', 'floralAccent'],
  },
  {
    id: 'kitchen',
    label: 'Kitchen',
    floor: 0,
    bounds: { minX: 3, maxX: 12, minZ: -11, maxZ: 1 },
    defaultWallpaper: 'paintedPlaster',
    wallpaperIds: ['paintedPlaster', 'linenWarm', 'geometricAccent'],
  },
  {
    id: 'powder',
    label: 'Guest Bath',
    floor: 0,
    bounds: { minX: 3, maxX: 12, minZ: 1, maxZ: 11 },
    defaultWallpaper: 'geometricAccent',
    wallpaperIds: ['geometricAccent', 'paintedPlaster', 'jacquardSoft'],
  },
  {
    id: 'master',
    label: 'Master Bedroom',
    floor: 1,
    bounds: { minX: -12, maxX: -3, minZ: -11, maxZ: 0 },
    defaultWallpaper: 'linenWarm',
    wallpaperIds: ['linenWarm', 'floralAccent', 'fabricNeutral'],
  },
  {
    id: 'bedroomEast',
    label: 'Bedroom East',
    floor: 1,
    bounds: { minX: 3, maxX: 12, minZ: -11, maxZ: 0 },
    defaultWallpaper: 'jacquardSoft',
    wallpaperIds: ['jacquardSoft', 'linenWarm', 'fabricNeutral'],
  },
  {
    id: 'bedroomWest',
    label: 'Bedroom West',
    floor: 1,
    bounds: { minX: -12, maxX: -3, minZ: 0, maxZ: 11 },
    defaultWallpaper: 'fabricNeutral',
    wallpaperIds: ['fabricNeutral', 'paintedPlaster', 'floralAccent'],
  },
  {
    id: 'bathWardrobe',
    label: 'Bath & Wardrobe',
    floor: 1,
    bounds: { minX: 3, maxX: 12, minZ: 0, maxZ: 11 },
    defaultWallpaper: 'paintedPlaster',
    wallpaperIds: ['paintedPlaster', 'geometricAccent', 'linenWarm'],
  },
  {
    id: 'balcony',
    label: 'Balcony',
    floor: 1,
    bounds: { minX: -5, maxX: 5, minZ: 11, maxZ: 15 },
    defaultWallpaper: 'concreteCalm',
    wallpaperIds: ['concreteCalm', 'paintedPlaster', 'linenWarm'],
  },
] as const;

/** PBR material texture sets used by room surfaces and architectural details. */
export const HOUSE_TEXTURES = {
  wallpapers: {
    linenWarm: {
      label: 'Warm Linen',
      color: '/textures/wallpapers/wallpaper_05.jpg',
      normal: '/textures/wallpapers/wallpaper_05_normal.jpg',
      roughness: '/textures/wallpapers/wallpaper_05_roughness.jpg',
      ao: '/textures/wallpapers/wallpaper_05_ao.jpg',
      height: '/textures/wallpapers/wallpaper_05_height.jpg',
      repeat: [2.2, 1.2] as const,
      roughnessValue: 0.86,
    },
    paintedPlaster: {
      label: 'Painted Plaster',
      color: '/textures/wallpapers/wallpaper_02.jpg',
      normal: '/textures/wallpapers/wallpaper_02_normal.jpg',
      roughness: '/textures/wallpapers/wallpaper_02_roughness.jpg',
      ao: '/textures/wallpapers/wallpaper_02_ao.jpg',
      height: '/textures/wallpapers/wallpaper_02_height.jpg',
      repeat: [2.8, 1.45] as const,
      roughnessValue: 0.92,
    },
    floralAccent: {
      label: 'Floral Accent',
      color: '/textures/wallpapers/wallpaper_03.jpg',
      normal: '/textures/wallpapers/wallpaper_03_normal.jpg',
      roughness: '/textures/wallpapers/wallpaper_03_roughness.jpg',
      ao: '/textures/wallpapers/wallpaper_03_ao.jpg',
      height: '/textures/wallpapers/wallpaper_03_height.jpg',
      repeat: [1.7, 1.05] as const,
      roughnessValue: 0.84,
    },
    fabricNeutral: {
      label: 'Fabric Neutral',
      color: '/textures/wallpapers/wallpaper_04.jpg',
      normal: '/textures/wallpapers/wallpaper_04_normal.jpg',
      roughness: '/textures/wallpapers/wallpaper_04_roughness.jpg',
      ao: '/textures/wallpapers/wallpaper_04_ao.jpg',
      repeat: [2.1, 1.1] as const,
      roughnessValue: 0.88,
    },
    jacquardSoft: {
      label: 'Soft Jacquard',
      color: '/textures/wallpapers/wallpaper_06.jpg',
      normal: '/textures/wallpapers/wallpaper_06_normal.jpg',
      roughness: '/textures/wallpapers/wallpaper_06_roughness.jpg',
      height: '/textures/wallpapers/wallpaper_06_height.jpg',
      repeat: [1.8, 1.0] as const,
      roughnessValue: 0.82,
    },
    geometricAccent: {
      label: 'Calm Geometry',
      color: '/textures/wallpapers/wallpaper_01.jpg',
      normal: '/textures/wallpapers/wallpaper_01_normal.jpg',
      roughness: '/textures/wallpapers/wallpaper_01_roughness.jpg',
      ao: '/textures/wallpapers/wallpaper_01_ao.jpg',
      height: '/textures/wallpapers/wallpaper_01_height.jpg',
      repeat: [3.0, 1.5] as const,
      roughnessValue: 0.9,
    },
    concreteCalm: {
      label: 'Concrete Calm',
      color: '/textures/walls/concrete.jpg',
      normal: '/textures/walls/concrete_normal.jpg',
      roughness: '/textures/walls/concrete_roughness.jpg',
      ao: '/textures/walls/concrete_ao.jpg',
      height: '/textures/walls/concrete_height.jpg',
      repeat: [4.0, 2.0] as const,
      roughnessValue: 0.94,
    },
  },
  surfaces: {
    woodFloor: {
      color: '/textures/floors/wood_floor.jpg',
      normal: '/textures/floors/wood_floor_normal.jpg',
      roughness: '/textures/floors/wood_floor_roughness.jpg',
      ao: '/textures/floors/wood_floor_ao.jpg',
      height: '/textures/floors/wood_floor_height.jpg',
      repeat: [5.6, 5.6] as const,
      roughnessValue: 0.7,
    },
    parquet: {
      color: '/textures/floors/parquet.jpg',
      normal: '/textures/floors/parquet_normal.jpg',
      roughness: '/textures/floors/parquet_roughness.jpg',
      ao: '/textures/floors/parquet_ao.jpg',
      height: '/textures/floors/parquet_height.jpg',
      repeat: [3.8, 3.8] as const,
      roughnessValue: 0.62,
    },
    kitchenTile: {
      color: '/textures/floors/kitchen_tile.jpg',
      normal: '/textures/floors/kitchen_tile_normal.jpg',
      roughness: '/textures/floors/kitchen_tile_roughness.jpg',
      ao: '/textures/floors/kitchen_tile_ao.jpg',
      height: '/textures/floors/kitchen_tile_height.jpg',
      repeat: [4.2, 4.2] as const,
      roughnessValue: 0.74,
    },
    bathTile: {
      color: '/textures/tiles/bathroom_tile.jpg',
      normal: '/textures/tiles/bathroom_tile_normal.jpg',
      roughness: '/textures/tiles/bathroom_tile_roughness.jpg',
      ao: '/textures/tiles/bathroom_tile_ao.jpg',
      height: '/textures/tiles/bathroom_tile_height.jpg',
      repeat: [3.4, 3.4] as const,
      roughnessValue: 0.58,
    },
    terrazzo: {
      color: '/textures/tiles/terrazzo_tile.jpg',
      normal: '/textures/tiles/terrazzo_tile_normal.jpg',
      roughness: '/textures/tiles/terrazzo_tile_roughness.jpg',
      ao: '/textures/tiles/terrazzo_tile_ao.jpg',
      height: '/textures/tiles/terrazzo_tile_height.jpg',
      repeat: [4.0, 4.0] as const,
      roughnessValue: 0.54,
    },
    oak: {
      color: '/textures/wood/oak_veneer.jpg',
      normal: '/textures/wood/oak_veneer_normal.jpg',
      roughness: '/textures/wood/oak_veneer_roughness.jpg',
      ao: '/textures/wood/oak_veneer_ao.jpg',
      height: '/textures/wood/oak_veneer_height.jpg',
      repeat: [2.5, 2.5] as const,
      roughnessValue: 0.57,
    },
    exteriorConcrete: {
      color: '/textures/walls/concrete.jpg',
      normal: '/textures/walls/concrete_normal.jpg',
      roughness: '/textures/walls/concrete_roughness.jpg',
      ao: '/textures/walls/concrete_ao.jpg',
      repeat: [6.0, 6.0] as const,
      roughnessValue: 0.96,
    },
  },
} as const;

/** External model placements. Paths are public URLs served by Vite. */
export const HOUSE_MODEL_PLACEMENTS = [
  { name: 'LivingSofa', path: '/models/furniture/sofa.gltf', position: [-8.6, 0, -2.6] as Vector3Tuple, rotationY: Math.PI * 0.5, fit: { width: 3.2, depth: 1.35, height: 1.1 }, collider: { halfExtents: [1.7, 0.55, 0.72] as Vector3Tuple, offset: [0, 0.55, 0] as Vector3Tuple } },
  { name: 'LivingCoffeeTable', path: '/models/furniture/coffee_table.gltf', position: [-6.2, 0, -2.7] as Vector3Tuple, rotationY: 0, fit: { width: 1.55, depth: 0.95, height: 0.55 }, collider: { halfExtents: [0.82, 0.28, 0.52] as Vector3Tuple, offset: [0, 0.28, 0] as Vector3Tuple } },
  { name: 'LivingTv', path: '/models/furniture/tv.gltf', position: [-3.25, 0, -3.1] as Vector3Tuple, rotationY: -Math.PI * 0.5, fit: { width: 1.6, depth: 0.25, height: 1.05 } },
  { name: 'LivingArmchair', path: '/models/furniture/armchair.gltf', position: [-8.9, 0, 2.9] as Vector3Tuple, rotationY: Math.PI * 0.75, fit: { width: 1.18, depth: 1.1, height: 1.05 }, collider: { halfExtents: [0.62, 0.55, 0.58] as Vector3Tuple, offset: [0, 0.55, 0] as Vector3Tuple } },
  { name: 'LivingBookshelf', path: '/models/furniture/bookshelf.gltf', position: [-11.55, 0, 5.5] as Vector3Tuple, rotationY: Math.PI * 0.5, fit: { width: 1.75, depth: 0.55, height: 2.2 }, collider: { halfExtents: [0.92, 1.1, 0.32] as Vector3Tuple, offset: [0, 1.1, 0] as Vector3Tuple } },
  { name: 'KitchenSet', path: '/models/kitchen/kitchen_set.glb', position: [7.6, 0, -10.25] as Vector3Tuple, rotationY: 0, fit: { width: 4.1, depth: 0.85, height: 1.22 }, collider: { halfExtents: [2.1, 0.65, 0.45] as Vector3Tuple, offset: [0, 0.65, 0] as Vector3Tuple } },
  { name: 'KitchenFridge', path: '/models/kitchen/fridge.glb', position: [11.25, 0, -8.4] as Vector3Tuple, rotationY: -Math.PI * 0.5, fit: { width: 0.9, depth: 0.9, height: 2.05 }, collider: { halfExtents: [0.5, 1.03, 0.5] as Vector3Tuple, offset: [0, 1.03, 0] as Vector3Tuple } },
  { name: 'DiningTable', path: '/models/kitchen/dining_table_pbr.gltf', position: [7.25, 0, -2.8] as Vector3Tuple, rotationY: Math.PI * 0.12, fit: { width: 2.15, depth: 1.2, height: 0.82 }, collider: { halfExtents: [1.12, 0.42, 0.66] as Vector3Tuple, offset: [0, 0.42, 0] as Vector3Tuple } },
  { name: 'DiningChairA', path: '/models/kitchen/chair_pbr.gltf', position: [7.25, 0, -4.1] as Vector3Tuple, rotationY: 0, fit: { width: 0.72, depth: 0.72, height: 0.92 } },
  { name: 'DiningChairB', path: '/models/kitchen/chair_pbr.gltf', position: [7.25, 0, -1.5] as Vector3Tuple, rotationY: Math.PI, fit: { width: 0.72, depth: 0.72, height: 0.92 } },
  { name: 'DiningChairC', path: '/models/kitchen/chair_pbr.gltf', position: [5.8, 0, -2.8] as Vector3Tuple, rotationY: -Math.PI * 0.5, fit: { width: 0.72, depth: 0.72, height: 0.92 } },
  { name: 'DiningChairD', path: '/models/kitchen/chair_pbr.gltf', position: [8.7, 0, -2.8] as Vector3Tuple, rotationY: Math.PI * 0.5, fit: { width: 0.72, depth: 0.72, height: 0.92 } },
  { name: 'PowderToilet', path: '/models/bathroom/toilet.glb', position: [10.4, 0, 3.8] as Vector3Tuple, rotationY: -Math.PI * 0.5, fit: { width: 0.72, depth: 0.85, height: 0.92 } },
  { name: 'PowderSink', path: '/models/bathroom/sink.glb', position: [11.35, 0, 6.0] as Vector3Tuple, rotationY: -Math.PI * 0.5, fit: { width: 0.88, depth: 0.55, height: 0.96 } },
  { name: 'PowderMirror', path: '/models/bathroom/mirror.gltf', position: [11.78, 1.0, 6.0] as Vector3Tuple, rotationY: -Math.PI * 0.5, fit: { width: 0.95, depth: 0.18, height: 1.15 } },
  { name: 'MasterBed', path: '/models/bedrooms/bed_double.glb', position: [-8.1, 3.2, -6.8] as Vector3Tuple, rotationY: Math.PI * 0.5, fit: { width: 2.45, depth: 2.55, height: 1.2 }, collider: { halfExtents: [1.28, 0.45, 1.33] as Vector3Tuple, offset: [0, 0.45, 0] as Vector3Tuple } },
  { name: 'MasterWardrobe', path: '/models/bedrooms/wardrobe.gltf', position: [-11.4, 3.2, -1.3] as Vector3Tuple, rotationY: Math.PI * 0.5, fit: { width: 1.85, depth: 0.65, height: 2.2 }, collider: { halfExtents: [0.96, 1.1, 0.34] as Vector3Tuple, offset: [0, 1.1, 0] as Vector3Tuple } },
  { name: 'BedroomEastBed', path: '/models/bedrooms/bed_single.glb', position: [8.0, 3.2, -6.6] as Vector3Tuple, rotationY: -Math.PI * 0.5, fit: { width: 1.35, depth: 2.2, height: 1.0 }, collider: { halfExtents: [0.74, 0.42, 1.14] as Vector3Tuple, offset: [0, 0.42, 0] as Vector3Tuple } },
  { name: 'BedroomEastDesk', path: '/models/bedrooms/desk.gltf', position: [11.4, 3.2, -2.0] as Vector3Tuple, rotationY: -Math.PI * 0.5, fit: { width: 1.5, depth: 0.72, height: 0.85 } },
  { name: 'BedroomWestBed', path: '/models/bedrooms/bed_single.glb', position: [-8.2, 3.2, 5.4] as Vector3Tuple, rotationY: Math.PI * 0.5, fit: { width: 1.35, depth: 2.2, height: 1.0 }, collider: { halfExtents: [0.74, 0.42, 1.14] as Vector3Tuple, offset: [0, 0.42, 0] as Vector3Tuple } },
  { name: 'BedroomWestNightstand', path: '/models/bedrooms/bedside_table.glb', position: [-10.0, 3.2, 3.9] as Vector3Tuple, rotationY: 0, fit: { width: 0.65, depth: 0.55, height: 0.62 } },
  { name: 'BathTub', path: '/models/bathroom/bathtub.glb', position: [8.0, 3.2, 6.4] as Vector3Tuple, rotationY: Math.PI, fit: { width: 2.05, depth: 1.0, height: 0.78 }, collider: { halfExtents: [1.08, 0.42, 0.55] as Vector3Tuple, offset: [0, 0.42, 0] as Vector3Tuple } },
  { name: 'BathSink', path: '/models/bathroom/sink.glb', position: [11.35, 3.2, 2.0] as Vector3Tuple, rotationY: -Math.PI * 0.5, fit: { width: 0.9, depth: 0.55, height: 0.95 } },
  { name: 'BalconyRailingFront', path: '/models/exterior/balcony_railing.glb', position: [0, 3.2, 15.0] as Vector3Tuple, rotationY: 0, fit: { width: 9.6, depth: 0.22, height: 1.05 } },
  { name: 'BalconyRailingLeft', path: '/models/exterior/balcony_railing.glb', position: [-5.0, 3.2, 13.0] as Vector3Tuple, rotationY: Math.PI * 0.5, fit: { width: 4.0, depth: 0.22, height: 1.05 } },
  { name: 'BalconyRailingRight', path: '/models/exterior/balcony_railing.glb', position: [5.0, 3.2, 13.0] as Vector3Tuple, rotationY: Math.PI * 0.5, fit: { width: 4.0, depth: 0.22, height: 1.05 } },
  { name: 'HousePlantLiving', path: '/models/decor/plant.gltf', position: [-10.6, 0, -8.6] as Vector3Tuple, rotationY: Math.PI * 0.25, fit: { width: 0.85, depth: 0.85, height: 1.28 } },
  { name: 'PaintingLiving', path: '/models/decor/painting.gltf', position: [-11.78, 1.42, -2.0] as Vector3Tuple, rotationY: Math.PI * 0.5, fit: { width: 1.28, depth: 0.16, height: 0.92 } },
  { name: 'CurtainsLiving', path: '/models/decor/curtains.glb', position: [-9.0, 0.02, -10.88] as Vector3Tuple, rotationY: 0, fit: { width: 2.2, depth: 0.16, height: 2.45 } },
] as const;

/** Performance-oriented defaults used by model integration. */
export const HOUSE_RENDERING_CONFIG = {
  TEXTURE_ANISOTROPY: 4,
  PRELOAD_TEXTURE_BATCH_SIZE: 6,
  USE_HEIGHT_MAPS: false,
  MODEL_ENV_INTENSITY: 0.72,
  MODEL_OPAQUE_ROUGHNESS_MIN: 0.42,
  MODEL_CAST_SHADOWS: false,
  LOD_PROXY_DISTANCE: 34,
  MAX_SHADOWED_INTERIOR_LIGHTS: 1,
} as const;
